### ISSUE TITLE
[backup-appdata.sh] If you keep the `List containers and assiciated config directory to stop and backup` empty, the script will stop.

### ISSUE THREAD

**Issue by TRaSH-** [Drazzilb08/userScripts#4]
- If you keep the `List containers and assiciated config directory to stop and backup` empty, the script will stop.
- with posting this error i also noticed a typo: shouldn't `assiciated` be `associated` ?

**Comment by Drazzilb08** [comment]
> If you keep the List containers and assiciated config directory to stop and backup empty, the script will stop.
Not 100% sure on this one.
I've ran it through with nothing within the list array with the expected result 
I've also ran through with nothing in the no_stop_list array with the expected result.

Could you please supply me with the combination that produces this result 

> with posting this error i also noticed a typo: shouldn't assiciated be associated ?
fixed with commit [ef90a7b](https://github.com/Drazzilb08/userScripts/commit/ef90a7bdfd04d34b1b50dd955d03b2fe2638b014)

**Comment by TRaSH-** [comment]
doesn't happen any more with v1.3.8
