### ISSUE TITLE
renamer.py does not use source_override when set to hardlink

### ISSUE THREAD

**Issue by supermariobruh** [Drazzilb08/userScripts#57]
When using renamer.py the script will only use the override directory if the file name in the override and source directories match, even if the override directory is a closer match to the *arr folder.

**Comment by Drazzilb08** [comment]
When I get some time I'll try to trouble shoot this down.

**Comment by Drazzilb08** [comment]
@supermariobruh 
I know it's been quite some time since I went through this but I have been Fck'd with work and all
However, I cannot duplicate this based upon the title of this issue.
However to the points. of the comment you left. 
>  the script will only use the override directory if the file name in the override and source directories match
This is expected behavior as the script assumes that you have downloaded assets from TPDB based upon their naming scheme  (which is based upon TMDB)

> even if the override directory is a closer match to the *arr folder.
The matching process doesn't happen until much later in the script. The initial process of sorting through movies/shows and collections happens at the beginning. So if you have two files `The Lord of the Rings` and `Lord of the Rings` It won't care that the first one is a better match since the script just assumes that they are different files and possibly different movies all together. If they were named EXACTLY the same then it will use the override path over the source directory.
